
#define BOOST_CHRONO_HEADER_ONLY 1
#define BOOST_ERROR_CODE_HEADER_ONLY 1
#define BOOST_UBLAS_MOVE_SEMANTICS
#define BOOST_UBLAS_TYPE_CHECK 0
#define BOOST_UBLAS_USE_LONG_DOUBLE
#define BOOST_NO_EXCEPTIONS
#define BOOST_HAS_FLOAT128
#define BOOST_HAS_CLOCK_GETTIME 1
#define BOOST_HAS_NANOSLEEP 1
#define BOOST_HAS_NRVO 1
#define BOOST_HAS_STDINT_H 1
